Huge improvement on the Docky.

diff --git a/bin/docky b/bin/docky
--- a/bin/docky
+++ b/bin/docky
@@ -1,33 +1,68 @@
 #!/bin/bash
-PLATFORMS=("woocommerce" "magento" "eccube")
-PACKAGE_LOCATION="https://github.com/guzzilar"
 
-version_folder=".version"
-execute_command=""
-build_folder=""
+DOCKY_VERSION="0.1.0-dev"
+DOCKY_RELEASE_DATE="Jul 21, 2017"
+DOCKY_EXECUTABLE_COMMANDS=("doc" "up" "build" "version")
+SUPPORTED_PLATFORMS=("woocommerce" "magento" "eccube")
+REPOSITORY_ACCOUNT="https://github.com/guzzilar"
+VERSIONING_LOCATION=".version"
+
+app_name=""
+build_location=""
 build_platform=""
 build_source=""
 build_version="latest"
+container_base_location="containers"
+container_location=""
 
-##
-# Show the usage of Docky.
-##
-doc() {
-    echo -e ''
-    echo -e 'usage: docky build [--platform=<name>] [--target=<version>]'
-    echo -e ''
-    echo -e '--platform\tSpecify the target platform that you want to build'
-    echo -e '--target\tSpecify the target version that you want to build'
-    echo -e ''
+the_command=""
+arg_position=0
+
+###
+ # Docky's document
+ ##
+doc () {
+    echo -e "Docky Document:"
+    echo -e "---------------"
+    echo -e "usage: docky build [<name>] [--version=<version>]"
+    echo -e ""
+    echo -e "\t--version\tSpecify the target version that you want to build"
 }
 
-##
-# Check if Docky supports a build target platform.
-#
-hasPlatform() {
+###
+ # Docky's version
+ ##
+version () {
+    echo -e ".."
+    echo -e "Docky v$DOCKY_VERSION (released at $DOCKY_RELEASE_DATE)"
+}
+
+###
+ # Check if Docky supports a build target platform.
+ #
+ # @param $1 string  name of a platform you want to check
+ ##
+canExecute () {
+    local the_command
+
+    for the_command in ${DOCKY_EXECUTABLE_COMMANDS[@]}; do
+        [[ $the_command == $1 ]] && {
+            return 0
+        }
+    done
+
+    return 1
+}
+
+###
+ # Check if Docky supports a build target platform.
+ #
+ # @param $1 string  name of a platform you want to check
+ ##
+isSupportPlatform () {
     local platform
 
-    for platform in ${PLATFORMS[@]}; do
+    for platform in ${SUPPORTED_PLATFORMS[@]}; do
         [[ $platform == $1 ]] && {
             return 0
         }
@@ -36,56 +71,73 @@ hasPlatform() {
     return 1
 }
 
-##
-# Preparation
-#
-initialize() {
-    echo "###################################################"
-    echo "Docky: Checking the container version.."
-    if [ ! -d $version_folder ]; then
-        mkdir -p $version_folder
-        echo " > Created a new folder, $version_folder."
+###
+ # Container version checking
+ ##
+fetchContainer () {
+    local container_version=$(curl -s https://api.github.com/repos/guzzilar/docker-$build_platform/git/refs/heads/master | jq '.object.sha' | sed -e 's/^"//' -e 's/"$//')
+    container_location=$container_base_location/$build_platform
+
+    echo "Docky: checking the container version.."
+
+    # Check for base container directory.
+    if [ ! -d $container_location ]; then
+        mkdir -p $container_location
+        echo " > Created a $container_location directory."
     fi
 
-    local container_version=$(curl -s https://api.github.com/repos/guzzilar/docker-woocommerce/git/refs/heads/master | jq '.object.sha' | sed -e 's/^"//' -e 's/"$//')
+    # Check for container versioning directory.
+    if [ ! -d $container_base_location/.versions ]; then
+        mkdir -p $container_base_location/.versions
+        echo " > Created a $container_base_location/.versions directory."
+    fi
 
-    if [ ! -f "$version_folder/docker-$build_platform.$container_version" ]; then
-        rm $version_folder/docker-$build_platform.*
-        touch $version_folder/docker-$build_platform.$container_version
+    # Cache a versioning file.
+    if [ ! -f "$container_base_location/.versions/docker-$build_platform.$container_version" ]; then
         echo " > Found a new version of docker-$build_platform (commit: $container_version)"
-        echo " > Cached: $version_folder/docker-$build_platform.$container_version"
+
+        rm -f $container_base_location/.versions/docker-$build_platform.*
+        touch $container_base_location/.versions/docker-$build_platform.$container_version
+
+        echo " > Cached \"$container_base_location/.versions/docker-$build_platform.$container_version\""
+    else
+        echo " > The container is up-to-date."
+    fi
+}
+
+###
+ # Preparation
+ ##
+initialize () {
+    local package_location="$REPOSITORY_ACCOUNT/docker-$build_platform/archive/master.zip"
+    build_location="app/$([[ ! -z $app_name ]] && echo $app_name || echo $build_platform)"
+
+    fetchContainer
+
+    echo ".."
+    echo "."
+    echo "Docky: preparing docker..."
+
+    if [ ! -d $build_location ]; then
+        mkdir -p $build_location
+        echo " > Created a $build_location directory."
+    else
+        echo " > Cannot create a new app, $build_location already exists."
     fi
 
-    ## TODO : Will continue later...
-
-    build_folder="deploy/$build_platform"
-    local package_location="$PACKAGE_LOCATION/docker-$build_platform/archive/master.zip"
-
-    echo "***************************************"
-    echo "Docky: Preparing docker..."
-
-    if [ ! -d $build_folder ]; then
-        echo "Docky: Build directory: $build_folder "
-        mkdir -p $build_folder
-    fi
-
-    [[ ! -d $build_folder/src && ! -f $build_folder/tmp/docker-$build_platform.zip ]] && {
+    [[ ! -d $container_location/src && ! -f $container_location/tmp/docker-$build_platform.zip ]] && {
         # 1. Download.
-        mkdir $build_folder/tmp
-        echo "Docky: Downloading a Docker package from $package_location."
+        mkdir $container_location/tmp
+        echo "Docky: downloading a Docker package from $package_location."
         echo "Docky: ================================================================================"
-        wget -O $build_folder/tmp/docker-$build_platform.zip $package_location
+        wget -O $container_location/tmp/docker-$build_platform.zip $package_location
 
         # 2. Unzip
+        echo "Docky: unzip $container_location/tmp/docker-$build_platform.zip"
         echo "Docky: ================================================================================"
-        unzip $build_folder/tmp/docker-$build_platform.zip -d $build_folder/tmp/
-        echo "Docky: Moving file to $build_folder."
-        mv $build_folder/tmp/docker-$build_platform-master/* $build_folder
-
-        # 3. Remove.
-        echo "Docky: ================================================================================"
-        echo "Docky: Removing $build_folder/tmp directory."
-        rm -R $build_folder/tmp
+        unzip $container_location/tmp/docker-$build_platform.zip -d $container_location/tmp/
+        echo "Docky: moving file to $container_location."
+        mv $container_location/tmp/docker-$build_platform-master/* $container_location
     }
 }
 
@@ -93,31 +145,45 @@ initialize() {
 # Boot up a container!
 #
 up() {
+    echo ".."
+    echo "Docky: running up \"$build_platform\" version \"$build_version\" container.."
+
     initialize
 
     echo "Docky: Booting up the docker!"
     echo "Docky: ================================================================================"
-    $build_folder/bin/start $build_version --build --source=$build_source
+
+    $container_location/bin/docky-servant up $build_version $build_location
 }
 
 ##
 # Build it!
 #
 build() {
+    echo ".."
+    echo "Docky: running up \"$build_platform\" version \"$build_version\" container.."
+
     initialize
 
-    echo "Docky: Building the docker!"
+    echo "Docky: Booting up the docker!"
     echo "Docky: ================================================================================"
-    $build_folder/bin/start $build_version --re-build --source=$build_source
+
+    $container_location/bin/docky-servant build $build_version $build_location
 }
 
-# $1 cannot be empty.
-# And the first argument must be "build".
-execute_command=$1
-[[ -z $execute_command || $execute_command != "up" && $execute_command != "build" ]] && {
+# ..
+#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
+# EXECUTION AREA
+#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
+# ..
+the_command=$1
+if ! canExecute $the_command; then
+    echo ".."
+    echo "Docky: error, cannot execute \"$the_command\"."
+    echo ""
     doc
     exit
-}
+fi
 
 # Remove "execute command" from arguments.
 shift
@@ -141,8 +207,9 @@ while [[ $# -gt 0 ]]; do
                 IFS=":"
                 target=($1)
 
-                if ! hasPlatform ${target[0]}; then
-                    echo "error: platform \"$1\" did not match any platform(s) Docky supported."
+                if ! isSupportPlatform ${target[0]}; then
+                    echo ".."
+                    echo "Docky: error, platform \"$1\" did not match with any platform(s) I supported."
                     exit
                 fi
 
@@ -150,12 +217,24 @@ while [[ $# -gt 0 ]]; do
                 build_version=$([[ ! -z ${target[1]} ]] && echo ${target[1]} || echo "latest")
 
                 IFS=$OIFS
+                arg_position=1
+
+                shift
+                continue
             }
-            shift
+
+            [[ $arg_position -eq 1 ]] && {
+                app_name=$1
+
+                shift
+                continue
+            }
             ;;
     esac
 done
 
-[[ ! -z $build_platform ]] && {
-    $execute_command
-}
+$the_command
+
+# [[ ! -z $build_platform ]] && {
+    # $execute_command
+# }
